### ISSUE TITLE
Digitising Failed

### ISSUE THREAD

**Issue by totalitarian** [jamesf91/RemarkableSync#13] opened 2021-08-17 15:29 UTC
Note sure why but i've started getting this error from yesterday. Any ideas or information required from me to help debug?

**Comment by charlie-normand** [comment] 2021-10-25 14:54
Same issue, are there any logs that give more detail, does anyone know?

**Comment by jamesf91** [comment] 2022-08-27 14:46
duplicate of #28 which is now closed

**Closed as completed by jamesf91** 2022-08-27 14:46 UTC
